### ISSUE TITLE
Documentation to the columns of the csv files in the repository

### ISSUE THREAD

**Issue by akjagadish** [arjundevraj/rational-categorization#1]
Hi Arjun,

I was trying to fit rational categorization models and found your dataset via Tom Griffiths.
I was wondering if you can add or let me know the column names of your dataset so I can use them in our model fitting procedure.

Regards,

Akshay

**Comment by arjundevraj** [comment]
Hi Akshay,

My apologies for the delayed reply! As you must be aware, the behavioral data is available in this repository. In the CSV files, each row corresponds to data for a participant, and the value in each column (besides the first) reflects whether the participant selected category 1 or 2. The first column specifically tells you which CSV file was used as the stimulus sequence for the participant. You can match that to the specific file of with name stim_list_{x}.csv (where x is the integer in the first column) in https://github.com/arjundevraj/word_categorization/tree/master/stimuli to get the exact stimulus sequence that was shown to the participant. The integer values in each of these CSV files correspond to stimuli in the order that we list them in the paper. If you are only concerned with Experiment 1 data, then this should be sufficient to fit your model to our data (even values of x for stim_list_{x}.csv correspond to the control condition and odd values correspond to the experimental condition).  

For Experiment 2 data, you can use the value of k = (x - 100) % 6  where x is the same value of the first column used to identify the stimulus sequence file. If k = 1, then it is the control with no exceptions; k = 2 is the experimental condition with no exceptions; k = 3 is the experimental condition with 2 exceptions; k = 4 is the control condition with 2 exceptions; k = 5 is experimental condition with 4 exceptions; and k = 0 is the control condition with 4 exceptions. Again, knowing the number of exceptions and the stimulus sequence file, you can map the integer values directly to stimuli since the integers [0,...,13] correspond directly to the stimuli listed in the paper, in the exact same order. Please let me know if you have any other questions, and I would be happy to help!

Best,
Arjun

**Comment by akjagadish** [comment]
Dear Arjun,

Thanks a lot for taking the time to provide the details. It is indeed very helpful :) 
I had one question, how do we know which category the stimuli in the stim_list files belong to?

PS: I would be happy to make a PR with the csv file containing the entire data once I have it. 

Regards,

Akshay
